# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CastledDemoObejctiveC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Castled', :path => '../../'
  pod 'CastledInbox', :path => '../../'

  # Pods for CastledDemoObejctiveC

  target 'CastledDemoObejctiveCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CastledDemoObejctiveCUITests' do
    # Pods for testing
  end

end

target 'CNotificationContentDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'CastledNotificationContent', :path => '../../'
  # Pods for CNotificationContentDemo

end

target 'CNotificationServiceDemo' do
  use_frameworks!

  # Comment the next line if you don't want to use dynamic frameworks
  pod 'CastledNotificationService', :path => '../../'

  
end
