name: Publish IOS sdk on Cocoapods

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          
          
          pod lib lint Castled.podspec --allow-warnings
          #pod lib lint CastledInbox.podspec --allow-warnings
          pod lib lint CastledNotificationService.podspec --allow-warnings
          pod lib lint CastledNotificationContent.podspec --allow-warnings
          
          pod trunk push Castled.podspec --allow-warnings
          #pod trunk push CastledInbox.podspec --allow-warnings
          pod trunk push CastledNotificationService.podspec --allow-warnings
          pod trunk push CastledNotificationContent.podspec --allow-warnings

        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
